// Ported verbatim from the live single-file build. The entry.* IDs map to a
// specific Google Form; they are NOT the API's questionId and cannot be
// regenerated by hand. Changing one silently drops that column.
// Form: 1BYvr5QogSvf3hO39VYUZ9rKArQpPWQEwj7f7SbuZtXw

export const FORM_POST =
  'https://docs.google.com/forms/d/e/1FAIpQLScxiO0Zp9-hWvCU-Hz8GrojoCKAMf5huflxDsNNH_XotTfmzA/formResponse'

/** Contact fields captured at the gate, after the ten questions. */
export const CONTACT_FIELDS = {
  company: 'entry.1847603292',
  name: 'entry.342936001',
  email: 'entry.565810067',
  phone: 'entry.548638896',
  region: 'entry.669657284',
} as const

/** Computed values posted alongside the answers. */
export const RESULT_FIELDS = {
  score: 'entry.667769839',
  grade: 'entry.94753441',
} as const

export type Scored = [label: string, points: number]

export interface Question {
  area: string
  field: string
  t: string
  /** false = a fit/profile question that does not contribute to the score */
  score?: false
  o: string[] | Scored[]
}

export const QUESTIONS: Question[] = [
  {
    area: 'Fit', field: 'entry.2033019157', score: false,
    t: 'Which sector do you want more of?',
    o: ['Medical, dental or veterinary clinics', 'Restaurant and retail fit-outs', 'Childcare centres', 'Industrial and warehouse', 'Office build-outs', 'Pharmacy', 'Something else'],
  },
  {
    area: 'Can they find you', field: 'entry.94847149',
    t: 'When an owner searches for a contractor who builds your kind of project, where do you appear?',
    o: [['Top of page one', 3], ['Somewhere on page one', 2], ['Not sure', 1], ['Nowhere', 0]],
  },
  {
    area: 'Is work coming in', field: 'entry.1127033124',
    t: 'Where does your work come from today?',
    o: [['We already run ads', 3], ['Referrals plus some inbound from search', 2], ['Mostly brokers and architects', 1], ['Almost all referrals and repeat clients', 0]],
  },
  {
    area: 'How fast you reply', field: 'entry.400411152',
    t: 'How fast does a new inquiry get its first reply?',
    o: [['Within minutes', 3], ['Same day', 2], ['Next day', 1], ['Whenever someone gets to it', 0]],
  },
  {
    area: 'Who checks a job first', field: 'entry.1480494227',
    t: 'Before your estimator gets involved, who checks sector, size, budget and timeline?',
    o: [['A set process every time', 3], ['Whoever picks up the phone', 1], ['Nobody, everything goes to the estimator', 0]],
  },
  {
    area: 'Who checks a job first', field: 'entry.40289008',
    t: 'How often do you bid work you could not staff if you won it?',
    o: [['Rarely', 3], ['Sometimes', 1], ['Often', 0]],
  },
  {
    area: 'Who chases quotes', field: 'entry.1369176754',
    t: 'A quote goes quiet for three weeks. What happens?',
    o: [['Automated follow up runs for weeks', 3], ['Someone remembers to chase', 1], ['Nothing happens', 0]],
  },
  {
    area: 'What a job costs to win', field: 'entry.1064870871',
    t: 'Can you say what a signed project costs you to win, by source?',
    o: [['Yes, cost per signed project by source', 3], ['Roughly', 1], ['No idea', 0]],
  },
  {
    area: 'Fit', field: 'entry.18820584', score: false,
    t: 'What is your typical project size?',
    o: ['Under $100k', '$100k to $400k', '$400k to $1M', 'Over $1M'],
  },
  {
    area: 'Fit', field: 'entry.1506521833', score: false,
    t: 'If the plan needed ad budget for 90 days, could you fund it?',
    o: ['Yes', 'Not sure, depends on the number', 'No'],
  },
]

export const GAPS: Record<string, [title: string, body: string]> = {
  'Can they find you': ['Owners cannot find you', 'The people who will sign your next contract are searching right now and landing on a competitor. Search and paid put you in that moment, on terms owners actually type.'],
  'Is work coming in': ['You are one relationship away from a quiet quarter', 'Referrals are the best lead you will get, but they cannot be turned up when the schedule thins. A second channel you control is what makes next year predictable.'],
  'How fast you reply': ['You are answering after the decision is made', 'Owners call two or three firms in an afternoon. The first credible reply usually walks the space. Minutes matter more than polish here.'],
  'Who checks a job first': ['Your estimator is your most expensive filter', 'Every unqualified inquiry that reaches estimating costs you a day you could have spent on work you can actually staff. Qualify on sector, size, budget and permit stage first.'],
  'Who chases quotes': ['Quotes are dying of silence', 'Most projects that go quiet are not lost, they are delayed. Nothing chases them, so they get awarded to whoever called back.'],
  'What a job costs to win': ['You cannot scale what you cannot see', 'Without cost per signed project by source, every marketing decision is a guess and the good channel gets cut with the bad one.'],
}

export function gradeFor(pct: number): { grade: string; line: string } {
  if (pct >= 75) return { grade: 'Dialled in', line: 'The machine is mostly there. The gap below is what is still costing you contracts.' }
  if (pct >= 45) return { grade: 'Leaking', line: 'The work is coming in, but it is leaking on the way to your estimator.' }
  return { grade: 'Invisible', line: 'Almost everything is running on referrals and memory. That is fixable, and quickly.' }
}
